Add direct raw value access for calculated fields
trocco-io/embulk-input-kintone pull request #44
Opened 2024-04-30 03:55 UTC by pn-koshikawa

2024-05-01 05:42 UTC, pn-koshikawa commented
### result
- https://devhopjsm.cybozu.com/k/122/ 
- 数値（例：1000）-> test6
- 数値（例：1,000）-> test7

#### before
```
+--------------+--------------+-------------+-------------+------------+------------+-------------+-------------+
| テスト6:boolean | テスト7:boolean | テスト6:string | テスト7:string |  テスト6:long |  テスト7:long | テスト6:double | テスト7:double |
+--------------+--------------+-------------+-------------+------------+------------+-------------+-------------+
|        false |        false |    31622400 |    31622400 | 31,622,400 | 31,622,400 |   3.16224E7 |   3.16224E7 |
+--------------+--------------+-------------+-------------+------------+------------+-------------+-------------+
```

#### after
```
+--------------+--------------+-------------+-------------+------------+------------+-------------+-------------+
| テスト6:boolean | テスト7:boolean | テスト6:string | テスト7:string |  テスト6:long |  テスト7:long | テスト6:double | テスト7:double |
+--------------+--------------+-------------+-------------+------------+------------+-------------+-------------+
|        false |        false |    31622400 |    31622400 | 31,622,400 | 31,622,400 |   3.16224E7 |   3.16224E7 |
+--------------+--------------+-------------+-------------+------------+------------+-------------+-------------+
```

2024-05-09 08:31 UTC, Pasukaru1996 approved these changes
LGTM :owl:

2024-05-10 02:55 UTC, d-hrs requested changes
Please test with non-numeric data in `CALC` type.

2024-05-10 02:55 UTC, d-hrs commented on src/test/java/org/embulk/input/kintone/TestKintoneAccessor.java
> +        testRecord.putField("計算", new CalcFieldValue("1.23E-12"));
please add test case like
```
        testRecord.putField("計算(time)", new CalcFieldValue("12:34:56"));
```

2024-05-10 04:32 UTC, d-hrs approved these changes
LGTM

2024-05-10 05:47 UTC, merged